// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update
//
// Model data is stored in models.data.json and expanded at runtime
// by models.loader.ts. This file re-exports for backward compatibility.

export { MODELS } from "./models.loader.js";
